name : Hoax Project Deploy
on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Pull from github to server
    runs-on: ubuntu-latest
    steps:
    - name: deploy main
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORTO }}
        script: |
          cd ${{ secrets.DIR }}
          git pull origin main