name : Panji Belajar Deploy 
on:
  push:
    branches: [ develop ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: test deploy dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORTO }}
        script: |
          cd ${{ secrets.DIR }}
          git pull origin main